version: 0.0.5.{build}

image: Visual Studio 2022

cache:
- C:\Users\appveyor\Documents\PowerShell\Modules\Pester
- C:\Users\appveyor\Documents\PowerShell\Modules\PowerShellGet

skip_branch_with_pr: true

skip_commits:
  author: appveyor

environment:
  GITHUB_TOKEN:
    secure: VBvtOx1GcfCw0CpszU3o51q+rXovGMjX25Ld2RUF3c2rF1kaGF+cF8OiB6U2fPbY

init:
- pwsh: |
    if ($env:APPVEYOR_REPO_TAG -eq 'true')
    {
        [version]$Version = $env:APPVEYOR_REPO_TAG_NAME -replace '^\D*' -replace '\D*$'
        [int]$Build = $env:APPVEYOR_BUILD_NUMBER
        $BuildVersion = $Version, ++$Build -join '.'
        Update-AppVeyorBuild -Version $BuildVersion
    }

build_script:
- pwsh: |
    $ShouldPackage = [bool]$env:APPVEYOR_REPO_TAG_NAME
    ./build.ps1 -Clean -InstallDependencies -Build -Package:$ShouldPackage -NewVersion $env:APPVEYOR_REPO_TAG_NAME -ErrorAction Stop

test_script:
- pwsh: |
    ./build.ps1 -Test -TestConfig @{
        Run = @{
            Throw = $true
        }
        TestResult = @{
            OutputPath   = 'TestResults.xml'
            OutputFormat = 'NUnitXml'
        }
        Should = @{
            # Don't stop on first error
            ErrorAction = 'Continue'
        }
    } -UploadTestResultUri https://ci.appveyor.com/api/testresults/nunit/$env:APPVEYOR_JOB_ID

artifacts:
- path: ./Build/**PSExpression*.nupkg
  name: NuGet package

# If we updated the version in the build step, then we should commit and push
before_deploy:
- pwsh: |
    if (-not (git status -s)) {return}

    git config user.name appveyor
    git config user.email appveyor@dustyfox.uk
    git config core.autocrlf false
    git config credential.helper store
    "https://$($env:GITHUB_TOKEN):x-oauth-basic@github.com`n" | Set-Content $HOME/.git-credentials -NoNewline

    git add *
    git commit -m "Updated version: $env:APPVEYOR_REPO_TAG_NAME"
    git push origin HEAD:main
    git tag -f $env:APPVEYOR_REPO_TAG_NAME
    git push -f --tags

deploy:
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: PSExpression $(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: VBvtOx1GcfCw0CpszU3o51q+rXovGMjX25Ld2RUF3c2rF1kaGF+cF8OiB6U2fPbY
  artifact: NuGet package
  on:
    APPVEYOR_REPO_TAG: true
