version: 0.0.{build}

image: Visual Studio 2022

cache:
- C:\Users\appveyor\Documents\PowerShell\Modules\Pester
- C:\Users\appveyor\Documents\PowerShell\Modules\PowerShellGet

skip_branch_with_pr: true

build_script:
- pwsh: |
    $ShouldPackage = [bool]$env:APPVEYOR_REPO_TAG_NAME
    ./build.ps1 -Clean -InstallDependencies -Build -Package:$ShouldPackage -ErrorAction Stop

test_script:
- pwsh: |
    ./build.ps1 -Test -TestConfig @{
        Run = @{
            Throw = $true
        }
        TestResult = @{
            OutputPath   = 'TestResults.xml'
            OutputFormat = 'NUnitXml'
        }
        Should = @{
            # Don't stop on first error
            ErrorAction = 'Continue'
        }
    } -UploadTestResultUri https://ci.appveyor.com/api/testresults/nunit/$env:APPVEYOR_JOB_ID

artifacts:
- path: ./Build/**PSExpression*.nupkg
  name: NuGet package

deploy:
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: PSExpression $(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: VBvtOx1GcfCw0CpszU3o51q+rXovGMjX25Ld2RUF3c2rF1kaGF+cF8OiB6U2fPbY
  artifact: NuGet package
  on:
    APPVEYOR_REPO_TAG: true
