version: 0.0.{build}

image: Visual Studio 2022

cache:
- C:\Users\appveyor\Documents\PowerShell\Modules\Pester
- C:\Users\appveyor\Documents\PowerShell\Modules\PowerShellGet

install:
- pwsh: ./build.ps1 -InstallDependencies

build_script:
- pwsh: ./build.ps1 -Build -Package

test_script:
- pwsh: |
    ./build.ps1 -Test -TestConfig @{
        Run = @{
            Throw = $true
        }
        TestResult = @{
            OutputPath   = 'TestResults.xml'
            OutputFormat = 'NUnitXml'
        }
        Should = @{
            # Don't stop on first error
            ErrorAction = 'Continue'
        }
    } -UploadTestResultUri https://ci.appveyor.com/api/testresults/nunit/$env:APPVEYOR_JOB_ID

artifacts:
- path: ./Build/**PSExpression*.nupkg
  name: NuGet package
