version: 0.0.{build}

image: Visual Studio 2022

cache:
- C:\Users\appveyor\Documents\PowerShell\Modules\Pester
- C:\Users\appveyor\Documents\PowerShell\Modules\PowerShellGet

skip_branch_with_pr: true

install:
- pwsh: |
    ./build.ps1 -InstallDependencies

build_script:
- pwsh: |
    ./build.ps1 -Build

test_script:
- pwsh: |
    ./build.ps1 -Test -TestConfig @{
        Run = @{
            Throw = $true
        }
        TestResult = @{
            OutputPath   = 'TestResults.xml'
            OutputFormat = 'NUnitXml'
        }
        Should = @{
            # Don't stop on first error
            ErrorAction = 'Continue'
        }
    } -UploadTestResultUri https://ci.appveyor.com/api/testresults/nunit/$env:APPVEYOR_JOB_ID

artifacts:
- path: ./Build/**PSExpression*.nupkg
  name: NuGet package

for:

- branches:
    except:
      - main

  deploy: off

- branches:
    only:
      - main

  configuration: Release

  deploy_script:
  - pwsh: |
      ./build.ps1 -Package
