version: 0.0.{build}

image: Visual Studio 2022

install:
- pwsh: ./build.ps1 -InstallDependencies

build_script:
- pwsh: ./build.ps1 -Build

test_script:
- pwsh: ./build.ps1 -Test -TestSettings @{OutputFormat = 'NUnitXml'} -UploadTestResultUri https://ci.appveyor.com/api/testresults/nunit/$env:APPVEYOR_JOB_ID
